//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClubCardsEntities : DbContext
    {
        public ClubCardsEntities()
            : base("name=ClubCardsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buyings> Buyings { get; set; }
        public virtual DbSet<ClubCards> ClubCards { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Enterprises> Enterprises { get; set; }
        public virtual DbSet<SendMail> SendMail { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Lotery> Lotery { get; set; }
        public virtual DbSet<EnterpCards> EnterpCards { get; set; }
    
        public virtual ObjectResult<selectAllEnterpCards_Result4> selectAllEnterpCards()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectAllEnterpCards_Result4>("selectAllEnterpCards");
        }
    
        public virtual ObjectResult<selectCardsForUser_Result1> selectCardsForUser(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectCardsForUser_Result1>("selectCardsForUser", idParameter);
        }
    }
}
