//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class selectAllEnterpCards_Result1
    {
        public int C_id { get; set; }
        public decimal Cost { get; set; }
        public Nullable<int> CountPoints { get; set; }
        public string Img { get; set; }
        public Nullable<int> EnterpId { get; set; }
        public Nullable<bool> Payment { get; set; }
        public string Type { get; set; }
        public int C_id1 { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
    }
}
